version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/api/web/sweets_api/staticfiles
  web:
    build:
          context: .
          dockerfile: Dockerfile.prod
    command: gunicorn sweets_api.django_core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/api/web/sweets_api/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  postgres_data:
  static_volume: